In [1]:
'1、创建array'
import numpy as np
a = np.array([t**2 for t in range(8)] )
b = np.zeros([2,2]) # 可以创建多维度数组
c = np.linspace(0,1,3)  #现性等分函数
d = np.array(range(8))
print(a,b,c,d)

[ 0  1  4  9 16 25 36 49] [[0. 0.]
 [0. 0.]] [0.  0.5 1. ] [0 1 2 3 4 5 6 7]


In [23]:
'2、访问array元素'
a = np.array([[1,2,4,5],[2,4,7,3],[2,5,3,9]])
# 访问第一行
print(a)
print('第一行',a[0])
print('第一列',a[:,0])
print('切片', a[0][1:3])
print('切片', a[0][:-2])
print('切片', a[0][::2])
b = a>3 #返回 bool数组
c = np.copy(a[a>3])#利用bool数组选取元素
c

[[1 2 4 5]
 [2 4 7 3]
 [2 5 3 9]]
第一行 [1 2 4 5]
第一列 [1 2 2]
切片 [2 4]
切片 [1 2]
切片 [1 4]


array([4, 5, 4, 7, 5, 9])

In [24]:
'3、array 运算'
a = np.array([[1,2,4],[2,4,5],[3,5,2]])
b = np.array([1,2,3])
c = np.array([2,3,4])
print(a)
print(b+c, b-c, b*c, b/2,b//2, b**2,b%2) #常见运算符重载
print('dim of a =', np.ndim(a)) #查看维度
print('shape of a = ', np.shape(a)) #查看大小
print('max of a =',a.max())
print('sum of a =',a.sum())
print(np.dot(b,c)) #点积
print(np.dot(a,b)) #矩阵乘法

[[1 2 4]
 [2 4 5]
 [3 5 2]]
[3 5 7] [-1 -1 -1] [ 2  6 12] [0.5 1.  1.5] [0 1 1] [1 4 9] [1 0 1]
dim of a = 2
shape of a =  (3, 3)
max of a = 5
sum of a = 28
20
[17 25 19]


In [26]:
'4、使用矩阵对象'
A = np.matrix([[1.0,2.0],[3.0,4.0]]) #创建矩阵
B = np.matrix(np.arange(1,3))
print('A=',A)
print('转置A.T=',A.T)
print('A的逆A.I=',A.I)
print('矩阵乘法A*A =',A*A)

A= [[1. 2.]
 [3. 4.]]
转置A.T= [[1. 3.]
 [2. 4.]]
A的逆A.I= [[-2.   1. ]
 [ 1.5 -0.5]]
矩阵乘法A*A = [[ 7. 10.]
 [15. 22.]]


In [28]:
'5、使用ufunc函数'
# numpy中的 ufunc具有向量化特征，
# 且用c语言实现速度很快

x = np.linspace(0,np.pi,5)
y = np.sin(x)#np.sin(x) 作用到x的每一个元素

np.sin(x,x) #第二个参数表示将返回值赋给x本身

'frompyfunc函数可将普通python函数转换成ufunc函数'

def f(x):
    y = x if x>= 0 else 0
    return(y)

uf = np.frompyfunc(f,1,1)  #三个参数依次为 pyfun,nin,nout
z = uf([1,2,-1])   #返回结果数据元素类型是 object

#使用array对象的 astype方法将其转换成 np.float32
z.astype('f4')

array([1., 2., 0.], dtype=float32)

In [36]:
'1,Series对象'
import numpy as np
import pandas as pd
s = pd.Series([1,np.nan,6,8])
s.index = ['one','two','three','four']
print(s)
print(s.index)

one      1.0
two      NaN
three    6.0
four     8.0
dtype: float64
Index(['one', 'two', 'three', 'four'], dtype='object')


In [44]:
dates = pd.date_range('20130101',periods=3)
df = pd.DataFrame(np.random.randn(3,4),
                  index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01  1.196815  1.687873 -0.582623 -0.649844
2013-01-02  0.203151  0.184775 -0.427757 -0.714962
2013-01-03  1.023323  0.207978  0.468928 -0.260669

In [ ]:
'3，导入excel文档创建DataFrame对象'
classmates = pd.read_excel('classmates.xlsx')
classmates.columns = ['name','age','gender']
classmates

In [ ]:
'4,增加行'
classmates.loc[3] = {'name':'安妮','age':24,'gender':'女'}
classmates = classmates.append(pd.DataFrame([['丽丽','女','21']],\
             columns=classmates.columns),ignore_index=True)
# ignore_index=True 表示索引重置
classmates

In [1]:
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[[4,2,1,7]])

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


In [4]:
x.ndim

2

In [6]:
list(x[4])

[16, 17, 18, 19]

In [10]:
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print( a.shape)

(4, 3)


In [11]:
import numpy as np
 
a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 ravel 函数之后：')
print (a.ravel())
print ('\n')
 
print ('以 F 风格顺序调用 ravel 函数之后：')
print (a.ravel(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[0 1 2 3 4 5 6 7]


以 F 风格顺序调用 ravel 函数之后：
[0 4 1 5 2 6 3 7]


In [12]:
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [13]:
np.ravel(a,order='F')

array([0, 4, 1, 5, 2, 6, 3, 7])

In [14]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
import numpy as np
 
a = np.arange(12).reshape(2,2,3)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (np.transpose(a))

原数组：
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


对换数组：
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [20]:
b = np.transpose(a,[2,1,0])
b[0][0]

array([0, 6])

In [24]:
b

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [23]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('获取数组中一个值：')
print(np.where(a==6))   
print(a[1,1,0])  # 为 6
print ('\n')
 
 
# 将轴 2 滚动到轴 0（宽度到深度）
 
print ('调用 rollaxis 函数：')
b = np.rollaxis(a,2,1)
print (b)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [0, 1, 1]
# 最后一个 0 移动到最前面
print(np.where(b==6))   
print ('\n')
 
# 将轴 2 滚动到轴 1：（宽度到高度）
 
print ('调用 rollaxis 函数：')
c = np.rollaxis(a,2,1)
print (c)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [1, 0, 1]
# 最后的 0 和 它前面的 1 对换位置
print(np.where(c==6))   
print ('\n')

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
获取数组中一个值：
(array([1]), array([1]), array([0]))
6


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1]), array([0]), array([1]))


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1]), array([0]), array([1]))




In [25]:
import numpy as np
 
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  
 
# 对 y 广播 x
b = np.broadcast(x,y)  
# 它拥有 iterator 属性，基于自身组件的迭代器元组
 
print ('对 y 广播 x：')
r,c = b.iters
 
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))
print ('\n')
# shape 属性返回广播对象的形状
 
print ('广播对象的形状：')
print (b.shape)
print ('\n')
# 手动使用 broadcast 将 x 与 y 相加
b = np.broadcast(x,y)
c = np.empty(b.shape)
 
print ('手动使用 broadcast 将 x 与 y 相加：')
print (c.shape)
print ('\n')
c.flat = [u + v for (u,v) in b]
 
print ('调用 flat 函数：')
print (c)
print ('\n')
# 获得了和 NumPy 内建的广播支持相同的结果
 
print ('x 与 y 的和：')
print (x + y)

对 y 广播 x：
1 4
1 5


广播对象的形状：
(3, 3)


手动使用 broadcast 将 x 与 y 相加：
(3, 3)


调用 flat 函数：
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [28]:
import numpy as np
 
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  
 
# 对 y 广播 x
b = np.broadcast(x,y)  
# 它拥有 iterator 属性，基于自身组件的迭代器元组
 
print ('对 y 广播 x：')
r,c = b.iters
 
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))

对 y 广播 x：
1 4
1 5


In [29]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [30]:
import numpy as np
 
a = np.arange(9)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [31]:
import numpy as np

a = np.arange(16).reshape(4, 4)
print('第一个数组：')
print(a)
print('\n')
print('默认分割（0轴）：')
b = np.split(a,2)
print(b)
print('\n')

print('沿垂直方向分割：')
c = np.split(a,2,1)
print(c)
print('\n')

print('沿水平方向分割：')
d= np.hsplit(a,2)
print(d)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


默认分割（0轴）：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


沿垂直方向分割：
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


沿水平方向分割：
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [32]:
import numpy as np
 
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [33]:
import numpy as np
 
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')
print ('传递了 Axis 参数。 会广播值数组来配输入数组。')
 
print ('沿轴 0 广播：')
print (np.insert(a,1,[11],axis = 0))
print ('\n')
 
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [39]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
print ('删除第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')
 
print ('包含从数组中删除的替代值的切片：')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print (np.delete(a, np.s_[::2]))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


包含从数组中删除的替代值的切片：
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


[ 1  2  3  4  5  6  7  8  9 10]
